# GitHub Configuration for xSystem
# Aerospace & Defense Standards Compliance

# Issue and PR templates configuration
issue_template:
  # Bug report template
  - name: Bug Report
    about: Report a bug in xSystem
    title: '[BUG] '
    labels: ['bug', 'needs-triage']
    body: .github/ISSUE_TEMPLATE/bug_report.md

  # Feature request template
  - name: Feature Request
    about: Suggest a new feature for xSystem
    title: '[FEATURE] '
    labels: ['enhancement', 'needs-triage']
    body: .github/ISSUE_TEMPLATE/feature_request.md

  # Security vulnerability template
  - name: Security Vulnerability
    about: Report a security vulnerability in xSystem
    title: '[SECURITY] '
    labels: ['security', 'critical', 'needs-triage']
    body: .github/ISSUE_TEMPLATE/security_vulnerability.md

# Pull request template
pull_request_template: .github/pull_request_template.md

# Repository settings
repository:
  # Default branch
  default_branch: main
  
  # Branch protection rules
  branch_protection:
    main:
      required_status_checks:
        strict: true
        contexts:
          - "Security & Compliance Scan"
          - "Quality Assurance & Compliance"
          - "Comprehensive Testing & Validation"
          - "Aerospace & Defense Compliance"
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      enforce_admins: true
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false

# Issue labels configuration
labels:
  # Priority labels
  - name: "priority: critical"
    color: "d73a4a"
    description: "Critical issue affecting safety or security"
  - name: "priority: high"
    color: "fbca04"
    description: "High priority issue"
  - name: "priority: medium"
    color: "0e8a16"
    description: "Medium priority issue"
  - name: "priority: low"
    color: "1d76db"
    description: "Low priority issue"

  # Type labels
  - name: "type: bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "type: enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "type: documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "type: security"
    color: "d73a4a"
    description: "Security vulnerability or concern"
  - name: "type: performance"
    color: "fbca04"
    description: "Performance improvement or issue"
  - name: "type: compliance"
    color: "0e8a16"
    description: "Standards compliance issue or enhancement"

  # Aerospace/Defense labels
  - name: "aerospace: safety-critical"
    color: "d73a4a"
    description: "Affects safety-critical systems"
  - name: "aerospace: mission-critical"
    color: "fbca04"
    description: "Affects mission-critical operations"
  - name: "aerospace: compliance"
    color: "0e8a16"
    description: "Standards compliance related"
  - name: "aerospace: performance"
    color: "1d76db"
    description: "Performance critical for aerospace"

  # Standards labels
  - name: "standard: nasa"
    color: "0e8a16"
    description: "NASA standards compliance"
  - name: "standard: ecss"
    color: "1d76db"
    description: "ECSS standards compliance"
  - name: "standard: do178c"
    color: "fbca04"
    description: "DO-178C aerospace certification"

  # Status labels
  - name: "status: needs-triage"
    color: "d93f0b"
    description: "Issue needs initial review"
  - name: "status: in-progress"
    color: "1d76db"
    description: "Work in progress"
  - name: "status: blocked"
    color: "fbca04"
    description: "Blocked by external dependency"
  - name: "status: ready-for-review"
    color: "0e8a16"
    description: "Ready for code review"
  - name: "status: approved"
    color: "0e8a16"
    description: "Approved for merge"

  # Component labels
  - name: "component: core"
    color: "1d76db"
    description: "Core system functionality"
  - name: "component: security"
    color: "d73a4a"
    description: "Security features"
  - name: "component: validation"
    color: "fbca04"
    description: "Data validation"
  - name: "component: io"
    color: "0e8a16"
    description: "Input/output operations"
  - name: "component: monitoring"
    color: "1d76db"
    description: "System monitoring"
  - name: "component: testing"
    color: "a2eeef"
    description: "Testing framework"
  - name: "component: documentation"
    color: "0075ca"
    description: "Documentation"

# Milestone configuration
milestones:
  - title: "v0.0.3 - Aerospace Compliance"
    description: "Enhanced aerospace and defense standards compliance"
    state: "open"
  - title: "v0.0.4 - Security Hardening"
    description: "Enhanced security features and vulnerability prevention"
    state: "open"
  - title: "v0.0.5 - Performance Optimization"
    description: "Performance improvements for mission-critical operations"
    state: "open"

# Code owners configuration
codeowners:
  - path: "src/exonware/xsystem/security/"
    owners: ["@exonware/security-team"]
  - path: "src/exonware/xsystem/validation/"
    owners: ["@exonware/compliance-team"]
  - path: "tests/"
    owners: ["@exonware/testing-team"]
  - path: "docs/"
    owners: ["@exonware/documentation-team"]
  - path: ".github/"
    owners: ["@exonware/maintainers"]

# Repository topics
topics:
  - "aerospace"
  - "defense"
  - "safety-critical"
  - "enterprise"
  - "python"
  - "security"
  - "compliance"
  - "nasa-standards"
  - "ecss-standards"
  - "do178c"
  - "mission-critical"
  - "performance"
  - "monitoring"
  - "validation"
  - "serialization"

# Repository description
description: "Enterprise-grade Python framework for aerospace and defense applications with NASA/ECSS/DO-178C compliance"

# Repository homepage
homepage: "https://exonware.com/xsystem"

# Repository visibility
visibility: "public"

# Security policy
security_and_analysis:
  advanced_security:
    status: "enabled"
  secret_scanning:
    status: "enabled"
  secret_scanning_push_protection:
    status: "enabled"
  dependency_graph:
    status: "enabled"
  code_scanning:
    status: "enabled"

# Dependabot configuration
dependabot:
  - package_ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open_pull_requests_limit: 10
    reviewers:
      - "@exonware/security-team"
    assignees:
      - "@exonware/maintainers"
    commit_message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "security"

# Issue and PR automation
automation:
  # Auto-label issues based on title
  - name: "Auto-label issues"
    on:
      issues:
        types: [opened]
    jobs:
      auto-label:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/labeler@v4
            with:
              configuration-path: .github/labeler.yml

  # Auto-assign security issues
  - name: "Auto-assign security issues"
    on:
      issues:
        types: [opened]
        labels: ["security"]
    jobs:
      auto-assign:
        runs-on: ubuntu-latest
        steps:
          - name: "Auto-assign to security team"
            uses: actions/github-script@v6
            with:
              script: |
                github.rest.issues.addAssignees({
                  issue_number: context.issue.number,
                  assignees: ['@exonware/security-team']
                })

# Repository rules
rules:
  - name: "Require security review for security issues"
    conditions:
      - base: "main"
        labels: ["security"]
    required_reviews:
      - type: "CODE_OWNER"
        reviewers: ["@exonware/security-team"]
    required_status_checks:
      - "Security & Compliance Scan"
      - "CodeQL Analysis"

  - name: "Require compliance review for aerospace changes"
    conditions:
      - base: "main"
        labels: ["aerospace:safety-critical", "aerospace:mission-critical"]
    required_reviews:
      - type: "CODE_OWNER"
        reviewers: ["@exonware/compliance-team"]
    required_status_checks:
      - "Aerospace & Defense Compliance"

# Repository settings
settings:
  # General settings
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  
  # Features
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: false
  
  # Default merge button
  default_merge_method: "squash"
  
  # Auto-delete head branches
  delete_branch_on_merge: true
  
  # Vulnerability alerts
  vulnerability_alerts: true
  
  # Security policy
  security_policy: true
  
  # Contributing guidelines
  contributing_guidelines: true
  
  # Code of conduct
  code_of_conduct: true
  
  # License
  license_template: "mit"
  
  # Git ignore template
  gitignore_template: "Python"
  
  # Issue templates
  issue_templates: true
  
  # Pull request templates
  pull_request_templates: true

# Repository health check
health_check:
  - name: "Security scanning enabled"
    check: "security_and_analysis.advanced_security.status"
    expected: "enabled"
  
  - name: "Dependency scanning enabled"
    check: "security_and_analysis.dependency_graph.status"
    expected: "enabled"
  
  - name: "Secret scanning enabled"
    check: "security_and_analysis.secret_scanning.status"
    expected: "enabled"
  
  - name: "Code scanning enabled"
    check: "security_and_analysis.code_scanning.status"
    expected: "enabled"

# Compliance reporting
compliance:
  standards:
    - name: "NASA-STD-8719.13"
      status: "compliant"
      last_audit: "2024-01-01"
    - name: "NASA-STD-8739.7"
      status: "compliant"
      last_audit: "2024-01-01"
    - name: "NASA-STD-8739.8"
      status: "compliant"
      last_audit: "2024-01-01"
    - name: "ECSS-E-ST-40C"
      status: "compliant"
      last_audit: "2024-01-01"
    - name: "ECSS-Q-ST-80C"
      status: "compliant"
      last_audit: "2024-01-01"
    - name: "DO-178C"
      status: "compliant"
      last_audit: "2024-01-01"

# Performance metrics
performance:
  test_coverage_threshold: 80
  security_scan_threshold: 100
  compliance_check_threshold: 100
  performance_benchmark_threshold: 95

# Documentation requirements
documentation:
  required_sections:
    - "Installation"
    - "Quick Start"
    - "API Reference"
    - "Examples"
    - "Safety Guidelines"
    - "Compliance Notes"
    - "Security Considerations"
    - "Performance Notes"
    - "Troubleshooting"
    - "Contributing"
    - "License"

# Testing requirements
testing:
  required_suites:
    - "unit"
    - "integration"
    - "core"
    - "performance"
    - "security"
    - "compliance"
  
  coverage_requirements:
    unit: 90
    integration: 80
    core: 95
    security: 100
    compliance: 100

# Security requirements
security:
  required_scans:
    - "bandit"
    - "safety"
    - "semgrep"
    - "codeql"
    - "dependency-review"
  
  vulnerability_thresholds:
    critical: 0
    high: 0
    medium: 5
    low: 10

# Compliance requirements
compliance:
  required_checks:
    - "nasa-standards"
    - "ecss-standards"
    - "do178c-compliance"
    - "security-standards"
    - "performance-standards"
  
  audit_frequency: "monthly"
  reporting_frequency: "quarterly"
